### ISSUE TITLE
Switch to ESLint

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fathom#7]
ESLint is objectively better (and more configurable).
Plus, it found these:

```
➜  fathom git:(master) ✗ npm run lint

> @ lint /Users/pdehaan/dev/github/fathom
> eslint .


/Users/pdehaan/dev/github/fathom/fathom.js
    6:7   error  'flatMap' is defined but never used       no-unused-vars
   10:7   error  'jsdom' is defined but never used         no-unused-vars
  222:44  error  'isBlock' is not defined                  no-undef
  243:10  error  'paragraphish' is defined but never used  no-unused-vars
  247:24  error  'str' is defined but never used           no-unused-vars

/Users/pdehaan/dev/github/fathom/test/test.js
  20:40  error  'node' is defined but never used  no-unused-vars
  35:30  error  'node' is defined but never used  no-unused-vars
  36:28  error  'node' is defined but never used  no-unused-vars

✖ 8 problems (8 errors, 0 warnings)
```

And my .eslintrc file looks like this:

```yaml
env:
  es6: true
  mocha: true
  node: true

extends:
  - eslint:recommended
```

**Comment by pdehaan** [comment]
We can also easily reject `var` declarations and prefer `let`+`const` instead by adding these 2 rules:

```yaml
rules:
  no-var: 2
  prefer-const: 2
```

> ✖ 35 problems (35 errors, 0 warnings)

**Comment by erikrose** [comment]
Looks great. Hooray for finding unused symbols.

I'm trying to configure it so it won't complain about unused args, which are useful for documentation. I can't seem to find a combination that doesn't throw a configuration error. Do you see what's wrong with this picture?
```
rules:
  no-unused-vars:
    - 2
    - vars: all
      args: never
```
